version: '2'

services:

  http2mqtt:
    image: chrisgunawardena/http2mqtt
    environment:
      SSL_HOST: mqtt.chris.gunawardena.id.au
    ports:
      - "443:443"
      - "1883:1883"
    volumes:
      - "/etc/letsencrypt:/etc/letsencrypt"
